<a href="https://colab.research.google.com/github/spalominor/programacionparaingenieria/blob/main/PALOMINOs_SI02_v20240418.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## «*Olvidaba que en todo combate entre el fanatismo y el sentido común, pocas veces logra este último imponerse*».
### [Marguerite Yourcenar](https://es.wikipedia.org/wiki/Marguerite_Yourcenar)

# SI 02 NumPy

Actividad individual.

Resuelva los siguientes ejercicios con códigos que se ajusten al PEP8. Recuerde incluir los comentarios en el código y documentar las funciones con docstrings al estilo de Google.

**Importante:**

**no se permite la utilización de ciclos (for or while) para resolver los ejercicios.**

**todos los ejercicios deben ser resueltos con NumPy.**

## Ejercicio 00

Cree el arreglo_00 de 15 **columnas** y 1000 **filas** de la siguiente manera:

* cinco columnas con números aleatorios provenientes de una distribución normal de media 0 y desviación típica 1. Utilice como semilla el número de su documento de identidad sumado con el número de la columna.

* cinco columnas con números aleatorios enteros en los siguientes intervalos: 200 a 300, 400 a 600, 0 a 360, 100 a 900, y 1000 a 2000. Utilice como semilla el número de su documento de identidad.

* cinco columnas con números aleatorios binarios (0,1)

Muestre el resultado y las características del arreglo.

In [72]:
# Escriba aquí su código
# Importar librerias
import numpy as np


def crear_arreglo_00():
    """
    Crea un arreglo de 15 columnas y 1000 filas con números aleatorios
    según una semilla correspondiente al número de identificación.

    Args:
    None

    Returns:
    numpy.ndarray: Arreglo de dimensiones (1000, 15) con los números aleatorios.
    """
    # Establecer la semilla basada en el número de documento de identidad
    np.random.seed(1035972895)

    # Crear cinco columnas con números aleatorios de distribución normal
    normal_columns = np.random.normal(0, 1, size=(1000, 5))

    # Crear cinco columnas con números aleatorios enteros en los intervalos
    integer_columns = np.column_stack(
        [
            np.random.randint(200, 301, size=1000),
            np.random.randint(400, 601, size=1000),
            np.random.randint(0, 361, size=1000),
            np.random.randint(100, 901, size=1000),
            np.random.randint(1000, 2001, size=1000),
        ]
    )

    # Crear cinco columnas con números aleatorios binarios
    binary_columns = np.random.randint(0, 2, size=(1000, 5))

    # Combinar las tres partes en un solo arreglo
    arreglo_00 = np.column_stack([normal_columns, integer_columns, binary_columns])

    return arreglo_00


# Crear el arreglo
arreglo_00 = crear_arreglo_00()

# Mostrar el resultado y las características del arreglo
print("Arreglo creado:")
print(arreglo_00)
print("\nDimensiones del arreglo:", arreglo_00.shape)
print("Tipo de datos del arreglo:", arreglo_00.dtype)
print("Valor máximo en el arreglo por columna:\n", np.max(arreglo_00, axis=0))
print("Valor mínimo en el arreglo por columna:\n", np.min(arreglo_00, axis=0))
print("Promedio de los elementos del arreglo:", np.mean(arreglo_00))


Arreglo creado:
[[-0.56187136 -0.38984938  0.42749364 ...  0.          1.
   1.        ]
 [-0.26627403  0.37220887  0.5332562  ...  0.          1.
   1.        ]
 [-0.86361292 -0.21867336 -1.75104086 ...  0.          1.
   0.        ]
 ...
 [-1.1852742  -2.76836999 -0.51846461 ...  1.          1.
   0.        ]
 [-1.12513659  0.32453167 -1.77272817 ...  0.          0.
   1.        ]
 [-0.47897356 -0.63743078  2.11104875 ...  1.          1.
   0.        ]]

Dimensiones del arreglo: (1000, 15)
Tipo de datos del arreglo: float64
Valor máximo en el arreglo por columna:
 [4.10061373e+00 2.81156818e+00 3.25958891e+00 3.06506420e+00
 2.82483447e+00 3.00000000e+02 6.00000000e+02 3.60000000e+02
 8.98000000e+02 2.00000000e+03 1.00000000e+00 1.00000000e+00
 1.00000000e+00 1.00000000e+00 1.00000000e+00]
Valor mínimo en el arreglo por columna:
 [  -3.45508493   -3.27484272   -3.07427361   -2.99604264   -2.99072352
  200.          400.            1.          100.         1000.
    0.            0.  

## Ejercicio 01

Cree dos arreglos, de 15 columnas y 20 filas cada uno, a partir del arreglo_00.

Calcule el producto elemento a elemento entre los dos arreglos creados

Muestre el resultado y las características del arreglo que contiene el producto elemento a elemento.

In [73]:
# Escriba aquí su código
# Importar librerias necesarias
import numpy as np


def crear_arreglo_01():
    """
    Crea dos arreglos de 15 columnas y 20 filas a partir del arreglo_00.

    Returns:
    tuple: Tupla con los dos arreglos creados.
    """
    # Crear los dos arreglos a partir del arreglo_00
    arreglo_00 = crear_arreglo_00()
    arreglo_01a = arreglo_00[:20, :]
    arreglo_01b = arreglo_00[20:40, :]

    return arreglo_01a, arreglo_01b


# Crear los arreglos
arreglo_01a, arreglo_01b = crear_arreglo_01()

# Calcular el producto elemento a elemento
producto = np.multiply(arreglo_01a, arreglo_01b)
# Forma alternativa arreglo_01a * arreglo_01b

# Mostrar el resultado y las características del arreglo resultante
print("Producto elemento a elemento:")
print(producto)
print("\nDimensiones del arreglo resultante:", producto.shape)
print("Tipo de datos del arreglo resultante:", producto.dtype)
print("Valor máximo en el arreglo resultante:", np.max(producto))
print("Valor mínimo en el arreglo resultante:", np.min(producto))
print("Promedio de los elementos del arreglo resultante:", np.mean(producto))


Producto elemento a elemento:
[[ 4.91533134e-01 -4.11636327e-01 -1.84157992e-01  2.39355345e-01
   8.55252097e-01  6.36560000e+04  2.20506000e+05  4.02480000e+04
   5.97960000e+04  2.24838600e+06  0.00000000e+00  1.00000000e+00
   0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [-2.63980599e-01 -4.91028884e-01 -5.26464533e-01  7.71657445e-02
  -2.31869398e-01  6.17500000e+04  1.75305000e+05  4.84650000e+04
   4.97919000e+05  1.70149000e+06  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 7.15270466e-01 -3.26095394e-01 -4.37521260e-01 -5.79996356e-01
  -1.69430499e+00  6.12370000e+04  1.91290000e+05  4.48000000e+03
   3.54320000e+04  2.13759000e+06  0.00000000e+00  1.00000000e+00
   0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [-7.55061931e-01 -6.16001150e-01  1.23000041e+00  1.33213792e-01
   2.15936159e-01  5.42500000e+04  3.47498000e+05  3.05270000e+04
   3.73602000e+05  2.24698400e+06  0.00000000e+00  0.00000000e+00
   1.00000000e+00  0.0000

## Ejercicio 02

Cree dos arreglos, de 10 columnas y 10 filas cada uno, a partir del arreglo_00.

Calcule el producto matricial entre los dos arreglos creados

Muestre el resultado y las características del arreglo que contiene el producto matricial.

In [74]:
# Escriba aquí su código
# Importar librerias necesarias
import numpy as np


def crear_arreglo_02():
    """
    Crea dos arreglos de 10 columnas y 10 filas a partir del arreglo_00.

    Returns:
    tuple: Tupla con los dos arreglos creados.
    """
    # Crear los dos arreglos a partir del arreglo_00
    arreglo_02a = arreglo_00[:10, :10]
    arreglo_02b = arreglo_00[10:20, :10]

    return arreglo_02a, arreglo_02b


# Crear los arreglos
arreglo_02a, arreglo_02b = crear_arreglo_02()

# Calcular el producto matricial
producto = np.dot(arreglo_02a, arreglo_02b)
# Forma alternativa arreglo_02a @ arreglo_02b

# Mostrar el resultado y las características del arreglo resultante
print("Producto matricial:")
print(producto)
print("\nDimensiones del arreglo resultante:", producto.shape)
print("Tipo de datos del arreglo resultante:", producto.dtype)
print("Valor máximo en el arreglo resultante:", np.max(producto))
print("Valor mínimo en el arreglo resultante:", np.min(producto))
print("Promedio de los elementos del arreglo resultante:", np.mean(producto))


Producto matricial:
[[-2.22810071e+03 -1.91519024e+03  1.59107533e+03 -1.92340879e+03
  -3.41520839e+03  6.15871029e+05  1.33513150e+06  2.80545818e+05
   1.70340814e+06  4.39279194e+06]
 [-1.54108874e+03 -1.66915077e+03  1.71094846e+03 -2.15456977e+03
  -3.19518787e+03  6.77725364e+05  1.38610087e+06  2.63028993e+05
   1.83949146e+06  4.37560553e+06]
 [-2.57084025e+03 -1.90905937e+03  1.68985586e+03 -1.86328875e+03
  -3.39282685e+03  5.75501741e+05  1.30895381e+06  2.62215489e+05
   1.68326347e+06  4.45551370e+06]
 [-2.10890600e+03 -1.98120180e+03  1.36900184e+03 -1.95590683e+03
  -3.05288995e+03  6.09309273e+05  1.33403893e+06  2.86064483e+05
   1.69055487e+06  4.21891331e+06]
 [-2.08654724e+03 -1.23158387e+03  1.08938614e+03 -1.51156249e+03
  -2.50016681e+03  5.07432860e+05  1.10063428e+06  2.80438348e+05
   1.32656991e+06  3.57618395e+06]
 [-2.81296016e+03 -2.26878341e+03  1.67889179e+03 -1.96724882e+03
  -3.70351112e+03  6.13390277e+05  1.40559248e+06  2.93784766e+05
   1.77982603

## Ejercicio 03

Cree un arreglo, de 15 columnas y 10 filas, a partir del arreglo_00.

Calcule y muestre la suma de cada una de las columnas y de cada una de las filas.

In [75]:
# Escriba aquí su código
# Importar librerias necesarias
import numpy as np


def crear_arreglo_03():
    """
    Crea un arreglo de 15 columnas y 10 filas a partir del arreglo_00

    Args:
    None

    Returns
    Retorna un arreglo de numpy según lo especificado
    """
    # Selecciona las 10 primeras filas y todas las columnas del arreglo_00
    arreglo_03 = arreglo_00[:10, :15]

    # Retorna el array areglo_03
    return arreglo_03


# Crear el arreglo solicitado
arreglo_03 = crear_arreglo_03()

# Calcular la suma de los elementos de las columnas
suma_columnas = np.sum(arreglo_03, axis=0)

# Calcular la suma de los elementos de las filas
suma_filas = np.sum(arreglo_03, axis=1)

# Mostrar la suma de las columnas y de las filas
print("Suma de cada columna:")
print(suma_columnas)
print("\nSuma de cada fila:")
print(suma_filas)


Suma de cada columna:
[-3.28307206e+00 -2.07584420e+00  6.59798011e-01 -2.00907397e+00
 -1.16244013e+00  2.54000000e+03  5.00400000e+03  1.59200000e+03
  4.00100000e+03  1.35390000e+04  4.00000000e+00  9.00000000e+00
  5.00000000e+00  7.00000000e+00  4.00000000e+00]

Suma de cada fila:
[2623.53048545 2740.80811567 2538.26185213 2582.27105102 2157.86506778
 2721.06633549 3248.04775825 2406.9451272  2618.54832489 3059.78524976]


## Ejercicio 04

Utilice el arreglo creado en el ejercicio anterior. Reconvierta el arreglo a uno de dimensión 5 columnas y 30 filas.

A partir de ese arreglo cree otro nuevo en el cual cada uno de los elementos de las filas es mayor que el promedio de la respectiva columna.

Muestre el arreglo obtenido y sus características.

In [76]:
# Escriba aquí su código
# Importar librerias necesarias
import numpy as np


def crear_arreglo_04():
    """
    Crea un arreglo donde cada uno de los elementos de las filas es mayor
    que el promedio de la respectiva columna del arreglo_03 reconvertido
    a 5 columas 30 filas

    Args:
    None

    Returns
    Un arreglo de numpy según las especificaciones
    """
    # Reconvertir el arreglo_03 a 5 columnas 30 filas
    arreglo_03r = arreglo_03.reshape(30, 5)

    # Calcular el array con el promedio de cada columna
    promedio_columnas = np.mean(arreglo_03r, axis=0)

    # Crear el arreglo_04 con la funcion condicional y where
    arreglo_04 = np.where(
        arreglo_03r > promedio_columnas, arreglo_03r, promedio_columnas + 1
    )

    # Retornar el arreglo
    return arreglo_04


# Crear el arreglo solicitado con la función anterior
arreglo_04 = crear_arreglo_04()

# Mostrar la información del arreglo
print("Arreglo obtenido:")
print(arreglo_04)
print("\nDimensiones del arreglo obtenido:", arreglo_04.shape)
print("Tipo de datos del arreglo obtenido:", arreglo_04.dtype)
print("Valor máximo en el arreglo obtenido:", np.max(arreglo_04))
print("Valor mínimo en el arreglo obtenido:", np.min(arreglo_04))
print("Promedio de los elementos del arreglo obtenido:", np.mean(arreglo_04))
print("Promedio de los elementos por cada columna:")
print(np.mean(arreglo_03.reshape(30, 5), axis=0))


Arreglo obtenido:
[[  85.69056426  168.03080519   54.2553266   134.53303087  452.39458533]
 [ 218.          429.          172.          396.         1407.        ]
 [  85.69056426  168.03080519   54.2553266   134.53303087  452.39458533]
 [  85.69056426  168.03080519   54.2553266   134.53303087  452.39458533]
 [ 247.          435.          135.          807.         1115.        ]
 [  85.69056426  168.03080519   54.2553266   134.53303087  452.39458533]
 [  85.69056426  168.03080519   54.2553266   134.53303087  452.39458533]
 [ 293.          470.           54.2553266   172.         1566.        ]
 [  85.69056426  168.03080519   54.2553266   134.53303087  452.39458533]
 [  85.69056426  168.03080519   54.2553266   134.53303087  452.39458533]
 [ 217.          593.           89.          426.         1256.        ]
 [  85.69056426  168.03080519   54.2553266   134.53303087  452.39458533]
 [  85.69056426  168.03080519   54.2553266   134.53303087  452.39458533]
 [ 274.          406.          22

## Ejercicio 05

Utilice el arreglo creado en el ejercicio 03.

Ordene cada columna de forma descendente, de mayor a menor, de forma independiente. Luego cree un nuevo arreglo con la concatenación de todas las columnas ordenadas.

Muestre el resultado y las características del arreglo.

In [77]:
# Escriba aquí su código
# Importar las librerias necesarias
import numpy as np


def crear_arreglo_05():
    """
    Crea un arreglo de numpy según las especificaciones. En base al arreglo_03
    ordena cada columna de manera descendente

    Args:
    None

    Returns:
    El arreglo de numpy especificado
    """
    # Crear el arreglo_05 organizado por columnas, del mayor al menor
    arreglo_05 = np.sort(arreglo_03, kind="mergesort", axis=0)[::-1]

    # Retornar el arreglo creado
    return arreglo_05


# Crear el arreglo solicitado
arreglo_05 = crear_arreglo_05()

# Imprimir el arreglo
print(arreglo_05)

# Imprimir información del arreglo
print("\nDimensiones del arreglo obtenido:", arreglo_05.shape)
print("Tipo de datos del arreglo obtenido:", arreglo_05.dtype)
print("Valor máximo en el arreglo obtenido:", np.max(arreglo_05))
print("Valor mínimo en el arreglo obtenido:", np.min(arreglo_05))
print("Promedio de los elementos del arreglo obtenido:", np.mean(arreglo_05))


[[ 4.43349116e-01  8.62823241e-01  2.16925722e+00  1.82473148e+00
   1.74914497e+00  2.96000000e+02  5.99000000e+02  3.20000000e+02
   8.07000000e+02  1.71500000e+03  1.00000000e+00  1.00000000e+00
   1.00000000e+00  1.00000000e+00  1.00000000e+00]
 [ 3.95697355e-01  3.72208869e-01  1.54927367e+00  1.34603430e+00
   6.07458026e-01  2.93000000e+02  5.93000000e+02  2.68000000e+02
   6.67000000e+02  1.70100000e+03  1.00000000e+00  1.00000000e+00
   1.00000000e+00  1.00000000e+00  1.00000000e+00]
 [ 4.71396607e-02  3.11392681e-01  5.33256197e-01  5.03724919e-01
   3.81408236e-01  2.74000000e+02  5.82000000e+02  2.29000000e+02
   5.89000000e+02  1.56600000e+03  1.00000000e+00  1.00000000e+00
   1.00000000e+00  1.00000000e+00  1.00000000e+00]
 [-1.64882823e-01  1.02711344e-01  4.27493639e-01 -1.97525842e-01
   3.42513293e-01  2.64000000e+02  5.41000000e+02  1.97000000e+02
   4.26000000e+02  1.44300000e+03  1.00000000e+00  1.00000000e+00
   1.00000000e+00  1.00000000e+00  1.00000000e+00]
 [-2

## Ejercicio 06

Cree un arreglo, de 9 columnas y 9 filas, a partir del arreglo_00.

Agregue una nueva columna al final del arreglo que contenga la suma de cada una de las filas y otra columna que contenga el promedio de las nueve columnas originales del arreglo.

Muestre el resultado y las características del arreglo.

In [78]:
# Escriba aquí su código
# Importar librerías necesarias
import numpy as np


def crear_arreglo_06():
    """
    Crea un nuevo arreglo añadiendo nuevas columnas a este que contienen la
    suma de cada fila y el promedio de las nueve columnas originales.

    Args:
    None

    Returns:
    numpy.ndarray: Arreglo con las especificaciones.
    """
    # Crear un nuevo arreglo de 9x9 a partir del arreglo_00
    arreglo_temporal = arreglo_00[:9, :9]

    # Calcular la suma de cada fila
    suma_filas = np.sum(arreglo_temporal, axis=1)

    # Calcular el promedio de las nueve columnas originales
    promedio_columnas = np.mean(arreglo_temporal, axis=0)

    # Unir las nuevas columnas como un arreglo
    nuevas_columnas = np.column_stack([suma_filas, promedio_columnas])

    # Crear el arreglo_06 y agregar las 2 nuevas columnas al arreglo
    arreglo_06 = np.hstack((arreglo_temporal, nuevas_columnas))

    return arreglo_06


# Crear el arreglo solicitado
arreglo_06 = crear_arreglo_06()

# Mostrar el resultado y las características del arreglo resultante
print("Arreglo obtenido:")
print(arreglo_06)
print("\nDimensiones del arreglo obtenido:", arreglo_06.shape)
print("Tipo de datos del arreglo obtenido:", arreglo_06.dtype)
print("Valor máximo en el arreglo obtenido:", np.max(arreglo_06))
print("Valor mínimo en el arreglo obtenido:", np.min(arreglo_06))
print("Promedio de los elementos del arreglo obtenido:", np.mean(arreglo_06))


Arreglo obtenido:
[[-5.61871360e-01 -3.89849385e-01  4.27493639e-01 -5.17400348e-01
  -1.42788710e+00  2.18000000e+02  4.29000000e+02  1.72000000e+02
   3.96000000e+02  1.21253049e+03 -3.46465471e-01]
 [-2.66274032e-01  3.72208869e-01  5.33256197e-01 -1.97525842e-01
  -6.33549519e-01  2.47000000e+02  4.35000000e+02  1.35000000e+02
   8.07000000e+02  1.62380812e+03 -1.69660912e-01]
 [-8.63612920e-01 -2.18673362e-01 -1.75104086e+00  1.34603430e+00
   1.74914497e+00  2.93000000e+02  4.70000000e+02  3.50000000e+01
   1.72000000e+02  9.70261852e+02 -9.88306293e-02]
 [-6.32098674e-01  3.11392681e-01 -1.56372884e+00  5.03724919e-01
  -3.48239063e-01  2.17000000e+02  5.93000000e+02  8.90000000e+01
   4.26000000e+02  1.32327105e+03 -1.75268960e-01]
 [ 4.71396607e-02 -1.09862662e+00  8.58097825e-02 -1.51176834e+00
   3.42513293e-01  2.74000000e+02  4.06000000e+02  2.29000000e+02
   1.83000000e+02  1.08986507e+03 -1.71538708e-01]
 [ 3.95697355e-01 -1.01374178e+00 -2.39801558e-01  1.82473148e+00
 

## Ejercicio 07

A partir de la columna del arreglo 00 que contiene los números enteros entre 0 y 360, genere un nuevo arreglo de 10 x 100.

Genere un nuevo arreglo en el que cada valor corresponda a la conversión de grados sexagesimales a radianes del arreglo que acaba de crear

Muestre el resultado y las características del arreglo.

In [79]:
# Escriba aquí su código
# Importar librerías necesarias
import numpy as np


def crear_arreglo_07():
    """
    Crea un arreglo a partir de la columna del arreglo_00 que contiene
    numeros aleatorios enteros entre 0 y 360. Cada valor corresponde a
    la conversión en radianes de ese arreglo.

    Args:
    None

    Returns:
    Un arreglo de numpy según lo especificado.
    """
    # Crear un arreglo temporal 10x100 con los numeros enteros entre 0 y 360
    arreglo_temporal = arreglo_00[:, 7].reshape(10, 100)

    # Crear el arreglo_07 con la respectiva conversión a radianes
    arreglo_07 = arreglo_temporal * np.pi / 180

    # Retornar el arreglo
    return arreglo_07


# Crear el arreglo solicitado
arreglo_07 = crear_arreglo_07()

# Mostrar el resultado y las características del arreglo resultante
print("Arreglo obtenido:")
print(arreglo_07)
print("\nDimensiones del arreglo obtenido:", arreglo_07.shape)
print("Tipo de datos del arreglo obtenido:", arreglo_07.dtype)
print("Valor máximo en el arreglo obtenido:", np.max(arreglo_07))
print("Valor mínimo en el arreglo obtenido:", np.min(arreglo_07))
print("Promedio de los elementos del arreglo obtenido:", np.mean(arreglo_07))


Arreglo obtenido:
[[3.00196631 2.35619449 0.61086524 1.55334303 3.99680399 1.37881011
  5.58505361 3.43829863 1.18682389 4.6774824  4.01425728 1.83259571
  0.40142573 5.06145483 5.00909495 2.46091425 4.39822972 5.93411946
  0.2268928  0.97738438 4.08407045 6.26573201 2.23402144 5.98647933
  1.09955743 5.23598776 0.54105207 5.65486678 1.72787596 2.0943951
  5.65486678 6.02138592 5.65486678 5.68977336 3.59537826 3.01941961
  5.75958653 0.50614548 5.56760031 0.26179939 5.23598776 2.11184839
  1.08210414 0.61086524 5.89921287 5.75958653 2.91469985 0.59341195
  3.42084533 2.11184839 4.25860337 1.18682389 0.19198622 5.48033385
  1.69296937 5.93411946 5.07890812 2.54818071 6.19591884 2.21656815
  5.131268   2.44346095 4.03171057 4.57276264 4.93928178 4.29350996
  5.46288056 1.76278254 3.76991118 0.43633231 4.11897703 0.71558499
  4.2062435  2.94960644 0.01745329 2.75762022 5.42797397 5.53269373
  3.12413936 1.8675023  5.20108117 1.06465084 6.17846555 0.76794487
  1.90240888 3.17649924 4.11897

## Ejercicio 08

Cree un arreglo, de 15 columnas y 15 filas seleccionadas aleatoriamente (utilice el número de su documento de identidad como semilla), a partir del arreglo_00.

Calcule y muestre el determinante del arreglo, la transpuesta y la inversa.

In [80]:
# Escriba aquí su código
# Importar librerias necesarias
import numpy as np


def crear_arreglo_08():
    """
    Crea un arreglo 15x15 seleccionado aleatoriamente del arreglo_00
    con la semilla del número de identificación

    Args:
    None

    Returns:
    Un arreglo de numpy según lo especificado
    """
    # Establecer la semilla basada en el número de documento de identidad
    np.random.seed(1035972895)

    # Seleccionar el indice aleatorio para las filas a seleccionar
    filas_seleccionadas = np.random.choice(1000 - 15)

    # Crear el arreglo 15x15 según las filas seleccionadas
    arreglo_08 = arreglo_00[filas_seleccionadas : filas_seleccionadas + 15, :]

    # Retornar el arreglo
    return arreglo_08


# Crear el arreglo solicitado
arreglo_08 = crear_arreglo_08()

# Imprimir el arreglo
print("Arreglo obtenido:")
print(arreglo_08)

# Calcular e imprimir la transpuesta
print("Transpuesta:")
print(arreglo_08.T)

# Calcular e imprimir el determinante
print("Determinante:")
print(np.linalg.det(arreglo_08))

# Calcular e imprimir la inversa
print("Inversa:")
print(np.linalg.inv(arreglo_08))


Arreglo obtenido:
[[ 6.88978229e-01  1.20090797e+00  2.26530335e-01 -2.98058505e-01
  -3.30231882e-01  2.26000000e+02  5.47000000e+02  9.20000000e+01
   3.04000000e+02  1.87900000e+03  0.00000000e+00  1.00000000e+00
   1.00000000e+00  1.00000000e+00  0.00000000e+00]
 [-7.53925201e-02 -9.66578012e-02  1.03444689e-01 -1.21325207e+00
   8.08058777e-01  2.60000000e+02  5.03000000e+02  6.50000000e+01
   3.67000000e+02  1.67800000e+03  0.00000000e+00  0.00000000e+00
   1.00000000e+00  1.00000000e+00  0.00000000e+00]
 [-2.91526493e-01 -7.88860874e-01 -1.04135193e+00  6.68891973e-01
   4.17573151e-01  2.27000000e+02  5.75000000e+02  1.80000000e+01
   1.82000000e+02  1.86900000e+03  1.00000000e+00  0.00000000e+00
   1.00000000e+00  0.00000000e+00  1.00000000e+00]
 [ 1.29085145e-01 -2.98096847e+00  1.21230407e+00 -1.88255168e+00
  -1.88238542e-02  2.71000000e+02  5.14000000e+02  1.54000000e+02
   6.47000000e+02  1.32300000e+03  1.00000000e+00  1.00000000e+00
   0.00000000e+00  0.00000000e+00  0.

## Ejercicio 09

Cree un arreglo, de 8 columnas y  8 filas, ambas seleccionadas aleatoriamente (utilice el número de su documento de identidad como semilla), a partir del arreglo_00.

Luego cree un arreglo de dimensión 1x8 con número reales aleatorios en el intervalo 0,10 (utilice el número de su documento de identidad como semilla).

Asuma que el primer arreglo representa los coeficientes de un sistema de ecuaciones lineales, y el segundo arreglo contiene las respectivas constantes. Encuentre la solución al sistema utilizando funciones de álgebra lineal de NumPy.

Muestre el valor de cada una de las variables que resuelve el sistema de ecuaciones.

In [81]:
# Escriba aquí su código
# Importar librerias necesarias
import numpy as np


def crear_arreglo_09():
    """
    Crea un arreglo de 8x8 seleccionado aleatoriamente del arreglo_00
    con la semilla del número de identificación, que es un arreglo de
    coeficientes. También crea un arreglo de constantes con numeros reales
    de 0 a 10 de tamaño 1x8

    Args:
    None

    Returns:
    numpy.ndarray: Arreglo de coeficientes del sistema de ecuaciones.
    numpy.ndarray: Arreglo de constantes del sistema de ecuaciones.
    """
    # Establecer la semilla basada en el número de documento de identidad
    np.random.seed(1035972895)

    # Seleccionar aleatoriamente 8 filas del arreglo_00
    filas_selec = np.random.choice(arreglo_00.shape[0], 8, replace=False)
    # Seleccionar aleatoriamente 8 columnas del arreglo_00
    columnas_selec = np.random.choice(arreglo_00.shape[1], 8, replace=False)

    # Seleccionar las entradas correspondientes a las filas y columnas
    arreglo_coeficientes = arreglo_00[filas_selec][:, columnas_selec]

    # Crear un arreglo de dimensiones 1x8 con números reales aleatorios
    arreglo_constantes = np.random.uniform(0, 10, size=(8, 1))

    # Retornar los arreglos solicitados
    return arreglo_coeficientes, arreglo_constantes


# Crear la matriz de coeficientes y de constantes
coeficientes, constantes = crear_arreglo_09()

# Obtener el vector solución x: Ax=b
solucion = np.linalg.solve(coeficientes, constantes)

# Imprimir el valor solución de cada una de las variables
print(solucion)


[[  1.03821876]
 [-11.70086634]
 [ -4.98103665]
 [-13.07952021]
 [-21.56384498]
 [-19.0662428 ]
 [  0.04109708]
 [  0.04591769]]
